### PR TITLE
test devel

### PR DESCRIPTION
**Pull request by ringabout**
https://github.com/nim-lang/Nim/actions/runs/6651227765/job/18072847902

It seems to somehow break Nim CI recently. Probably a regression of the devel branch

### CODE REVIEW

**Comment by nitely** [comment]
mmh, should I merge this?

> tests.nim(5, 15) Error: cannot open 'unicodedb/casing'

the error.

**Comment by ringabout** [comment]
I suppose we need to figure out the error first. Either

**Comment by nitely** [comment]
it's not the same error as the one in Nim's CI, weird

**Comment by nitely** [comment]
yeah, the error in Nim's CI looks like one that could have been prevented/workaround by adding devel to CI in this lib

**Comment by ringabout** [comment]
> it's not the same error as the one in Nim's CI, weird

Sorry, I didn't notice it uses docker which doesn't have a devel channel for Nim.

**Comment by nitely** [comment]
this is caused by [testing this lib in release mode](https://github.com/nim-lang/Nim/blob/0e45b01b210bbf1bc535cc73fcb3fe649a343168/testament/important_packages.nim#L169C21-L169C56). I've recently added a test that catches an exception that I only raise in debug mode.

**Comment by nitely** [comment]
[this should fix it](https://github.com/nitely/nim-unicodeplus/commit/cede632deffc681de2b037abbc2a14d2a21a2941)

**Comment by nitely** [comment]
The tests are very slow to run in debug mode, btw. So that's probably why release is set.

**Comment by nitely** [comment]
[I've also added tests in release mode](https://github.com/nitely/nim-unicodeplus/commit/8b178b83f6e1089e346c0638dc5d0ac8a90a0c05)

**Comment by ringabout** [comment]
Thank you!

**Pull request closed without merging**
